### ISSUE TITLE
Date parsing incorrect

### ISSUE THREAD

**Issue by srob650** [guessit-io/guessit#284] opened 2016-04-07 03:38 UTC
Guessit version 2.0.4
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)

Seems to be returning an incorrect datetime object with the month and day reversed under Python 3 only.  When running

`guessit('Stephen.Colbert.2016.04.05.mkv')`

it returns

`MatchesDict([('title', 'Stephen Colbert'), ('date', datetime.date(2016, 5, 4)), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])`

I tried adding `options='-Y'` for "year first" with no change.  This issue does not happen in Python 2.7.10 for me.

**Comment by Toilal** [comment] 2016-04-08 16:48
What's the locale of your computer ? I think the result depends on the locale, because I can't reproduce on my computer.

Most of the date recognition is done by [dateutil parser](https://dateutil.readthedocs.org/en/latest/parser.html)

**Comment by Diaoul** [comment] 2016-04-08 17:13
I'm not sure it should be based on current locale.

**Comment by Toilal** [comment] 2016-04-08 17:14
true, I need to check the dateutil module docs.

**Comment by Toilal** [comment] 2016-04-08 20:20
I've updated dateutil module and can reproduce the issue. Unit test are failing.

**Comment by Toilal** [comment] 2016-04-08 20:27
Seems related to this issue https://github.com/dateutil/dateutil/issues/158

Locking to `python-dateutil<2.5.2` seems to fix the problem. Do you run ubuntu ?

**Comment by Toilal** [comment] 2016-04-08 21:16
The issue was introduced by this upstream commit : https://github.com/dateutil/dateutil/commit/2d42e046d55b9fbbc0a2f41ce83fb8ec5de2d28b.

It's an enhancement in dateutil parser, but it make things harder for guessit ...

**Comment by srob650** [comment] 2016-04-09 02:08
Just catching up to this.  Thanks for the deep dive and temp fix, works great!

**Comment by pganssle** [comment] 2016-04-10 15:43
FYI, the correct dateutil issue is dateutil/dateutil#81 or dateutil/dateutil#217.

**Comment by Toilal** [comment] 2016-04-10 16:06
Thanks for pointing this out. Currently we've locked depency to previous
version, and are waiting future enhancement :)

Also thanks for the really clear answer provided in the comment of the
commit.

**Comment by sbraz** [comment] 2016-08-07 00:59
@Toilal I believe 2.5.3 fixes this? See the last comments on https://github.com/dateutil/dateutil/issues/217

**Comment by sbraz** [comment] 2016-08-07 13:26
Actually it does not seem to be fixed but it looks to me like this is a behaviour we should expect: we call `parser.parse` with `dayfirst=True` so we assume the day is first.
If we want to change this, we could simply change to `dayfirst_opts = [False, True]`.

**Comment by Coacher** [comment] 2016-08-12 20:49
2.5.3 doesn't solve anything.
@sbraz, reordering dayfirst options doesn't help either.
Python-3.4.3, dateutil-2.5.3:
```
>>> from dateutil import parser
>>> str(parser.parse('09.03.08', dayfirst=False, yearfirst=False))
'2008-09-03 00:00:00'
>>> str(parser.parse('09.03.08', dayfirst=False, yearfirst=True))
'2009-03-08 00:00:00'
>>> str(parser.parse('09.03.08', dayfirst=True, yearfirst=True))
'2009-08-03 00:00:00'
>>> str(parser.parse('09.03.08', dayfirst=True, yearfirst=False))
'2008-03-09 00:00:00'
```
The above listing shows that only `dayfirst=True, yearfirst=False` combo gives [the expected result](https://github.com/guessit-io/guessit/blob/master/guessit/test/rules/date.yml#L3). Thus it must be the first one to be tried. However, we have
```
>>> str(parser.parse('15.01.31', dayfirst=True, yearfirst=False))
'2031-01-15 00:00:00'
```
This breaks [the expected behaviour](https://github.com/guessit-io/guessit/blob/master/guessit/test/rules/date.yml#L8).

Currently there's no way to make recent dateutil comply with the expected guessit behaviour.

**Comment by Toilal** [comment] 2016-08-12 21:52
Thanks @Coacher for analyse, I initially conclude the same thing when the issue appears. Sadly, there's still no changes in current dateutil master. Maybe we should try to fix with a dateutil fork...

**Comment by sbraz** [comment] 2016-08-12 22:55
Or ship your own version of dateutil, like requests does with urllib3?

**Comment by pganssle** [comment] 2016-08-12 23:18
Until there is a way to specify parsing behavior in a more granular fashion, it would probably be easier to just parse the date more than once with different `dayfirst` and `yearfirst`  options and deduce the correct value from the results.

The four possible options are:
* MDY
* YMD (`yearfirst`)
* DMY (`dayfirst`)
* YDM (`yearfirst`, `dayfirst`)

You want a preference ordering like this, I guess: DMY, YMD, MDY, YDM, or some variation on that, correct? I can take a look a bit later and provide a suggestion, but I imagine you can just parse it twice with different values for `yearfirst` and `dayfirst`, then based on what it gave you in each case, you can infer the original ordering of the dates and return them in whatever order you prefer.

In future versions of `dateutil`, the `parserinfo` will be much more configurable to allow for formatting preferences.

Another option is to either pin your dependency to the old version or vendor a patched version in the meantime, but both of those have disadvantages. I can't say how long it will take to make the parser more configurable.

**Comment by Toilal** [comment] 2016-09-13 21:53
Fixed in current version.

**Closed by Toilal** 2016-09-13 21:53 UTC
Labels: Bug
