### ISSUE TITLE
the word 'storm' is not detected

### ISSUE THREAD

**Issue by clasick** [guessit-io/guessit#439] opened 2017-04-27 12:43 UTC
no matter what if your movie has the word 'storm' or 'Storm' in it, it just ignores the word.

try it with 'After the Storm 2016'.

really weird issue.

**Comment by ratoaq2** [comment] 2017-04-27 12:49
Can you post the guessit output together with guessit version? 

This seems exactly this issue: https://github.com/guessit-io/guessit/issues/296#issuecomment-225456242

**Comment by clasick** [comment] 2017-04-27 15:49
Here you go:

`>>> guessit('After.the.Storm.2016.720p.YIFY').get('title')`
`'After the'`

I'm using guessit (2.1.2)

**Comment by Toilal** [comment] 2017-04-27 20:34
I think it's because guessit thinks it's a subtitle marker (starting with st).

**Comment by ratoaq2** [comment] 2017-04-27 21:47
Until #296 is fixed, you can follow the same workaround as described here: https://github.com/guessit-io/guessit/issues/409#issuecomment-281165559

Passing a list of languages to be considered, you won't have that issue
`guessit -L en After.the.Storm.2016.720p.YIFY `

**Comment by ratoaq2** [comment] 2017-05-21 06:46
Closing this as a duplicate of #296 which remains open until it gets fixed.

**Closed by ratoaq2** 2017-05-21 06:46 UTC
Labels: duplicate
